// apps/docs/src/demos/vue/CardDemo.vue
<script setup lang="ts">
import { Card, Button } from '@moderno-ui/vue'
</script>

<template>
  <Card>
    <template #title>Plan Pro</template>
    Acceso a todas las funciones, soporte prioritario y facturación anual.
    <template #footer>
      <Button variant="secondary" size="sm" label="Cancelar" />
      <Button size="sm" label="Actualizar" />
    </template>
  </Card>
</template>

// apps/docs/src/demos/react/CardDemo.tsx
import { Card, Button } from '@moderno-ui/react'

export default function CardDemo() {
  return (
    <Card
      title="Plan Pro"
      footer={
        <>
          <Button variant="secondary" size="sm" label="Cancelar" />
          <Button size="sm" label="Actualizar" />
        </>
      }
    >
      Acceso a todas las funciones, soporte prioritario y facturación anual.
    </Card>
  )
}
