// packages/vue/src/AccordionRoot.vue
<script setup lang="ts">
import { computed, useId } from 'vue'
import * as accordion from '@zag-js/accordion'
import { useMachine, normalizeProps } from '@zag-js/vue'
import { provideAccordion } from './accordion-context'
import { parts } from '@moderno-ui/class-contract'

const props = defineProps<{
  defaultValue?: string[]
  modelValue?: string[]
  multiple?: boolean
  collapsible?: boolean
}>()
const emit = defineEmits<{ 'update:modelValue': [string[]] }>()

const service = useMachine(accordion.machine, {
  id: useId(),
  get defaultValue() {
    return props.defaultValue
  },
  get value() {
    return props.modelValue
  },
  get multiple() {
    return props.multiple
  },
  get collapsible() {
    return props.collapsible
  },
  onValueChange(d) {
    emit('update:modelValue', d.value)
  },
})
const api = computed(() => accordion.connect(service, normalizeProps))
provideAccordion(api)
</script>

<template>
  <div v-bind="api.getRootProps()" :class="parts.accordion.root"><slot /></div>
</template>

// packages/svelte/src/AccordionRoot.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import * as accordion from '@zag-js/accordion'
  import { useMachine, normalizeProps } from '@zag-js/svelte'
  import { setAccordionContext } from './accordion-context'
  import { parts } from '@moderno-ui/class-contract'

  let {
    defaultValue,
    value = $bindable(),
    multiple,
    collapsible,
    onValueChange,
    children,
  }: {
    defaultValue?: string[]
    value?: string[]
    multiple?: boolean
    collapsible?: boolean
    onValueChange?: (value: string[]) => void
    children?: Snippet
  } = $props()

  const id = $props.id()
  const service = useMachine(accordion.machine, {
    id,
    get defaultValue() {
      return defaultValue
    },
    get value() {
      return value
    },
    get multiple() {
      return multiple
    },
    get collapsible() {
      return collapsible
    },
    onValueChange(d) {
      value = d.value
      onValueChange?.(d.value)
    },
  })
  const api = $derived(accordion.connect(service, normalizeProps))
  setAccordionContext(() => api)
</script>

<div {...api.getRootProps()} class={parts.accordion.root}>{@render children?.()}</div>
