// packages/vue/src/Alert.vue
<script setup lang="ts">
import { cx, parts, type AlertVariant } from '@moderno-ui/class-contract'

const props = defineProps<{ variant?: AlertVariant; title?: string }>()
</script>

<template>
  <div :class="cx.alert({ variant: props.variant })" role="alert">
    <p v-if="title" :class="parts.alert.title">{{ title }}</p>
    <p :class="parts.alert.body"><slot /></p>
  </div>
</template>

// packages/svelte/src/Alert.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { cx, parts, type AlertVariant } from '@moderno-ui/class-contract'

  let {
    variant,
    title,
    children,
  }: {
    variant?: AlertVariant
    title?: string
    children?: Snippet
  } = $props()
</script>

<div class={cx.alert({ variant })} role="alert">
  {#if title}<p class={parts.alert.title}>{title}</p>{/if}
  <p class={parts.alert.body}>{@render children?.()}</p>
</div>
