// packages/vue/src/CarouselIndicator.vue
<script setup lang="ts">
import { useCarousel } from './carousel-context'
import { parts } from '@moderno/class-contract'

const props = defineProps<{ index: number }>()
const api = useCarousel('Indicator')
</script>

<template>
  <button v-bind="api.getIndicatorProps({ index: props.index })" :class="parts.carousel.indicator"></button>
</template>

// packages/svelte/src/CarouselIndicator.svelte
<script lang="ts">
  import { getCarouselContext } from './carousel-context'
  import { parts } from '@moderno-ui/class-contract'

  let { index }: { index: number } = $props()
  const api = getCarouselContext()
</script>

<button {...api().getIndicatorProps({ index })} class={parts.carousel.indicator}></button>
