// packages/vue/src/Combobox.vue
<script setup lang="ts">
import { computed, ref, useId } from 'vue'
import * as combobox from '@zag-js/combobox'
import { useMachine, normalizeProps } from '@zag-js/vue'
import { parts } from '@moderno-ui/class-contract'

export interface ComboboxItem {
  label: string
  value: string
  disabled?: boolean
}

// Control renders inline; panel is teleported to the body.
defineOptions({ inheritAttrs: false })

const props = defineProps<{
  label?: string
  items: ComboboxItem[]
  placeholder?: string
  defaultValue?: string[]
  modelValue?: string[]
  disabled?: boolean
}>()
const emit = defineEmits<{ 'update:modelValue': [string[]] }>()

const query = ref('')
const options = computed(() => {
  const q = query.value.trim().toLowerCase()
  if (!q) return props.items
  return props.items.filter((item) => item.label.toLowerCase().includes(q))
})
const collection = computed(() => combobox.collection({ items: options.value }))

const service = useMachine(combobox.machine, {
  id: useId(),
  get collection() {
    return collection.value
  },
  get defaultValue() {
    return props.defaultValue
  },
  get value() {
    return props.modelValue
  },
  get disabled() {
    return props.disabled
  },
  onValueChange(d) {
    emit('update:modelValue', d.value)
  },
  // Only typing narrows the list; selection/clear set the input programmatically
  // and must show the full list on the next open.
  onInputValueChange(d) {
    query.value = d.reason === 'input-change' ? d.inputValue : ''
  },
})
const api = computed(() => combobox.connect(service, normalizeProps))
</script>

<template>
  <div v-bind="api.getRootProps()" :class="parts.combobox.root">
    <label v-if="label != null" v-bind="api.getLabelProps()" :class="parts.combobox.label">{{ label }}</label>
    <div v-bind="api.getControlProps()" :class="parts.combobox.control">
      <input v-bind="api.getInputProps()" :class="parts.combobox.input" :placeholder="placeholder" />
      <button v-bind="api.getTriggerProps()" :class="parts.combobox.trigger">▾</button>
    </div>
    <Teleport v-if="api.open && options.length > 0" to="body">
      <div v-bind="api.getPositionerProps()" :class="parts.combobox.positioner">
        <ul v-bind="api.getContentProps()" :class="parts.combobox.content">
          <li
            v-for="item in options"
            :key="item.value"
            v-bind="api.getItemProps({ item })"
            :class="parts.combobox.item"
          >
            <span v-bind="api.getItemTextProps({ item })" :class="parts.combobox.itemText">{{ item.label }}</span>
            <span v-bind="api.getItemIndicatorProps({ item })" :class="parts.combobox.itemIndicator" aria-hidden="true">✓</span>
          </li>
        </ul>
      </div>
    </Teleport>
  </div>
</template>

// packages/svelte/src/Combobox.svelte
<script lang="ts">
  import * as combobox from '@zag-js/combobox'
  import { useMachine, normalizeProps, portal } from '@zag-js/svelte'
  import { parts } from '@moderno/class-contract'

  export interface ComboboxItem {
    label: string
    value: string
    disabled?: boolean
  }

  let {
    label,
    items,
    placeholder,
    defaultValue,
    value = $bindable(),
    disabled,
    onValueChange,
  }: {
    label?: string
    items: ComboboxItem[]
    placeholder?: string
    defaultValue?: string[]
    value?: string[]
    disabled?: boolean
    onValueChange?: (value: string[]) => void
  } = $props()

  let query = $state('')
  const options = $derived.by(() => {
    const q = query.trim().toLowerCase()
    if (!q) return items
    return items.filter((item) => item.label.toLowerCase().includes(q))
  })
  const collection = $derived(combobox.collection({ items: options }))

  const id = $props.id()
  const service = useMachine(combobox.machine, {
    id,
    get collection() {
      return collection
    },
    get defaultValue() {
      return defaultValue
    },
    get value() {
      return value
    },
    get disabled() {
      return disabled
    },
    onValueChange(d) {
      value = d.value
      onValueChange?.(d.value)
    },
    // Only typing narrows the list; selection/clear set the input programmatically
    // and must show the full list on the next open.
    onInputValueChange(d) {
      query = d.reason === 'input-change' ? d.inputValue : ''
    },
  })
  const api = $derived(combobox.connect(service, normalizeProps))
</script>

<div {...api.getRootProps()} class={parts.combobox.root}>
  {#if label != null}
    <label {...api.getLabelProps()} class={parts.combobox.label}>{label}</label>
  {/if}
  <div {...api.getControlProps()} class={parts.combobox.control}>
    <input {...api.getInputProps()} class={parts.combobox.input} {placeholder} />
    <button {...api.getTriggerProps()} class={parts.combobox.trigger}>▾</button>
  </div>
  {#if api.open && options.length > 0}
    <div use:portal {...api.getPositionerProps()} class={parts.combobox.positioner}>
      <ul {...api.getContentProps()} class={parts.combobox.content}>
        {#each options as item (item.value)}
          <li {...api.getItemProps({ item })} class={parts.combobox.item}>
            <span {...api.getItemTextProps({ item })} class={parts.combobox.itemText}>{item.label}</span>
            <span {...api.getItemIndicatorProps({ item })} class={parts.combobox.itemIndicator} aria-hidden="true">✓</span>
          </li>
        {/each}
      </ul>
    </div>
  {/if}
</div>
