// packages/vue/src/SheetClose.vue
<script setup lang="ts">
import { useSheet } from './sheet-context'
import { parts } from '@moderno-ui/class-contract'

withDefaults(defineProps<{ closeLabel?: string }>(), { closeLabel: 'Close' })

const api = useSheet('Close')
</script>

<template>
  <button v-bind="api.getCloseTriggerProps()" :class="parts.sheet.close" :aria-label="closeLabel">
    <slot>✕</slot>
  </button>
</template>

// packages/svelte/src/SheetClose.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { getSheetContext } from './sheet-context'
  import { parts } from '@moderno/class-contract'

  let { closeLabel = 'Close', children }: { closeLabel?: string; children?: Snippet } = $props()
  const api = getSheetContext()
</script>

<button {...api().getCloseTriggerProps()} class={parts.sheet.close} aria-label={closeLabel}>
  {#if children}{@render children()}{:else}✕{/if}
</button>
