// packages/vue/src/Splitter.vue
<script setup lang="ts">
import { computed, useId } from 'vue'
import * as splitter from '@zag-js/splitter'
import { useMachine, normalizeProps } from '@zag-js/vue'
import { parts } from '@moderno/class-contract'

export interface SplitterPanelDef {
  /** Unique id for the panel; content is provided via a slot of the same name. */
  id: string
  /** Minimum size of the panel, as a percentage. */
  minSize?: number | string
  /** Maximum size of the panel, as a percentage. */
  maxSize?: number | string
  /** Whether the panel can be collapsed to `collapsedSize`. */
  collapsible?: boolean
  /** The size of the panel when collapsed. */
  collapsedSize?: number | string
  /** How the panel behaves when the group is resized. */
  resizeBehavior?: 'preserve-relative-size' | 'preserve-pixel-size'
}

const props = defineProps<{
  panels: SplitterPanelDef[]
  orientation?: 'horizontal' | 'vertical'
  size?: number[]
  defaultSize?: number[]
  keyboardResizeBy?: number
  resizeTriggerLabel?: (beforeId: string, afterId: string) => string
}>()
const emit = defineEmits<{
  'update:size': [size: number[]]
  resizeStart: []
  resizeEnd: [size: number[]]
}>()

const service = useMachine(splitter.machine, {
  id: useId(),
  get panels() {
    return props.panels.map(({ id, minSize, maxSize, collapsible, collapsedSize, resizeBehavior }) => ({
      id,
      minSize,
      maxSize,
      collapsible,
      collapsedSize,
      resizeBehavior,
    }))
  },
  get orientation() {
    return props.orientation
  },
  get size() {
    return props.size
  },
  get defaultSize() {
    return props.defaultSize
  },
  onResize(d) {
    emit('update:size', d.size)
  },
  onResizeStart() {
    emit('resizeStart')
  },
  onResizeEnd(d) {
    emit('resizeEnd', d.size)
  },
  get keyboardResizeBy() {
    return props.keyboardResizeBy
  },
})
const api = computed(() => splitter.connect(service, normalizeProps))

function resizeTriggerLabelFor(beforeId: string, afterId: string): string {
  return props.resizeTriggerLabel ? props.resizeTriggerLabel(beforeId, afterId) : `Resize ${beforeId} and ${afterId}`
}
</script>

<template>
  <div v-bind="api.getRootProps()" :class="parts.splitter.root">
    <template v-for="(panel, index) in panels" :key="panel.id">
      <div v-bind="api.getPanelProps({ id: panel.id })" :class="parts.splitter.panel">
        <slot :name="panel.id" />
      </div>
      <div
        v-if="index < panels.length - 1"
        v-bind="api.getResizeTriggerProps({ id: `${panel.id}:${panels[index + 1].id}` })"
        :class="parts.splitter.resizeTrigger"
        :aria-label="resizeTriggerLabelFor(panel.id, panels[index + 1].id)"
      >
        <div
          v-bind="api.getResizeTriggerIndicator({ id: `${panel.id}:${panels[index + 1].id}` })"
          :class="parts.splitter.resizeTriggerIndicator"
        />
      </div>
    </template>
  </div>
</template>

// packages/svelte/src/Splitter.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import * as splitter from '@zag-js/splitter'
  import { useMachine, normalizeProps } from '@zag-js/svelte'
  import { parts } from '@moderno-ui/class-contract'

  export interface SplitterPanelDef {
    /** Unique id for the panel; content is provided via a snippet of the same name. */
    id: string
    /** Minimum size of the panel, as a percentage. */
    minSize?: number | string
    /** Maximum size of the panel, as a percentage. */
    maxSize?: number | string
    /** Whether the panel can be collapsed to `collapsedSize`. */
    collapsible?: boolean
    /** The size of the panel when collapsed. */
    collapsedSize?: number | string
    /** How the panel behaves when the group is resized. */
    resizeBehavior?: 'preserve-relative-size' | 'preserve-pixel-size'
  }

  function defaultResizeTriggerLabel(beforeId: string, afterId: string): string {
    return `Resize ${beforeId} and ${afterId}`
  }

  interface Props {
    panels: SplitterPanelDef[]
    orientation?: 'horizontal' | 'vertical'
    size?: number[]
    defaultSize?: number[]
    onResize?: (size: number[]) => void
    onResizeStart?: () => void
    onResizeEnd?: (size: number[]) => void
    keyboardResizeBy?: number
    resizeTriggerLabel?: (beforeId: string, afterId: string) => string
    /** Panel content: pass one snippet per panel id, e.g. `{#snippet sidebar()}...{/snippet}`. */
    [panelId: string]: unknown
  }

  let {
    panels,
    orientation,
    size,
    defaultSize,
    onResize,
    onResizeStart,
    onResizeEnd,
    keyboardResizeBy,
    resizeTriggerLabel = defaultResizeTriggerLabel,
    ...panelContent
  }: Props = $props()

  const id = $props.id()
  const service = useMachine(splitter.machine, {
    id,
    get panels() {
      return panels.map(({ id, minSize, maxSize, collapsible, collapsedSize, resizeBehavior }) => ({
        id,
        minSize,
        maxSize,
        collapsible,
        collapsedSize,
        resizeBehavior,
      }))
    },
    get orientation() {
      return orientation
    },
    get size() {
      return size
    },
    get defaultSize() {
      return defaultSize
    },
    onResize(d) {
      onResize?.(d.size)
    },
    onResizeStart() {
      onResizeStart?.()
    },
    onResizeEnd(d) {
      onResizeEnd?.(d.size)
    },
    get keyboardResizeBy() {
      return keyboardResizeBy
    },
  })
  const api = $derived(splitter.connect(service, normalizeProps))
</script>

<div {...api.getRootProps()} class={parts.splitter.root}>
  {#each panels as panel, index (panel.id)}
    <div {...api.getPanelProps({ id: panel.id })} class={parts.splitter.panel}>
      {@render (panelContent[panel.id] as Snippet | undefined)?.()}
    </div>
    {#if panels[index + 1]}
      <div
        {...api.getResizeTriggerProps({ id: `${panel.id}:${panels[index + 1].id}` })}
        class={parts.splitter.resizeTrigger}
        aria-label={resizeTriggerLabel(panel.id, panels[index + 1].id)}
      >
        <div
          {...api.getResizeTriggerIndicator({ id: `${panel.id}:${panels[index + 1].id}` })}
          class={parts.splitter.resizeTriggerIndicator}
        ></div>
      </div>
    {/if}
  {/each}
</div>
