// packages/svelte/src/Dialog.svelte
<script lang="ts">
  import * as dialog from '@zag-js/dialog'
  import { useMachine, normalizeProps, portal } from '@zag-js/svelte'
  import { cx, parts } from '@moderno-ui/class-contract'

  let {
    triggerLabel,
    title,
    description,
    closeLabel = 'Close',
  }: {
    triggerLabel: string
    title: string
    description?: string
    closeLabel?: string
  } = $props()

  const id = $props.id()
  const service = useMachine(dialog.machine, { id })
  const api = $derived(dialog.connect(service, normalizeProps))
</script>

<button {...api.getTriggerProps()} class={cx.button({ variant: 'primary' })}>{triggerLabel}</button>
{#if api.open}
  <div use:portal {...api.getBackdropProps()} class={parts.dialog.backdrop}></div>
  <div use:portal {...api.getPositionerProps()} class={parts.dialog.positioner}>
    <div {...api.getContentProps()} class={parts.dialog.content}>
      <h2 {...api.getTitleProps()} class={parts.dialog.title}>{title}</h2>
      {#if description}
        <p {...api.getDescriptionProps()} class={parts.dialog.desc}>{description}</p>
      {/if}
      <div class={parts.dialog.actions}>
        <button {...api.getCloseTriggerProps()} class={cx.button({ variant: 'secondary' })}>{closeLabel}</button>
      </div>
    </div>
  </div>
{/if}

// packages/react/src/dialog.tsx
import { useId, type ReactNode } from 'react'
import * as dialog from '@zag-js/dialog'
import { useMachine, normalizeProps, Portal } from '@zag-js/react'
import { cx, parts } from '@moderno-ui/class-contract'

export interface DialogProps {
  triggerLabel: string
  title: ReactNode
  description?: ReactNode
  closeLabel?: string
}

/**
 * Closed-prop Dialog (per ADR-0003): configured by props, not composed.
 * Behavior + a11y come from the Zag dialog machine; Moderno owns the markup
 * and the md-* class contract.
 */
export function Dialog({ triggerLabel, title, description, closeLabel = 'Close' }: DialogProps) {
  const service = useMachine(dialog.machine, { id: useId() })
  const api = dialog.connect(service, normalizeProps)

  return (
    <>
      <button {...api.getTriggerProps()} className={cx.button({ variant: 'primary' })}>
        {triggerLabel}
      </button>
      {api.open && (
        <Portal>
          <div {...api.getBackdropProps()} className={parts.dialog.backdrop} />
          <div {...api.getPositionerProps()} className={parts.dialog.positioner}>
            <div {...api.getContentProps()} className={parts.dialog.content}>
              <h2 {...api.getTitleProps()} className={parts.dialog.title}>
                {title}
              </h2>
              {description ? (
                <p {...api.getDescriptionProps()} className={parts.dialog.desc}>
                  {description}
                </p>
              ) : null}
              <div className={parts.dialog.actions}>
                <button {...api.getCloseTriggerProps()} className={cx.button({ variant: 'secondary' })}>
                  {closeLabel}
                </button>
              </div>
            </div>
          </div>
        </Portal>
      )}
    </>
  )
}
