// packages/solid/src/divider.tsx
import { Show, type JSX } from 'solid-js'
import { cx, parts, type DividerOrientation } from '@moderno-ui/class-contract'

export interface DividerProps {
  orientation?: DividerOrientation
  label?: JSX.Element
}

/** Visual/semantic separator, optionally labelled. Pure CSS, closed-prop. */
export function Divider(props: DividerProps) {
  const orientation = () => props.orientation ?? 'horizontal'
  return (
    <Show
      when={props.label && orientation() === 'horizontal'}
      fallback={
        <div
          class={cx.divider({ orientation: orientation() })}
          role="separator"
          aria-orientation={orientation() === 'vertical' ? 'vertical' : undefined}
        />
      }
    >
      <div class={parts.divider.group} role="separator">
        {props.label}
      </div>
    </Show>
  )
}

// packages/react/src/divider.tsx
import type { ReactNode } from 'react'
import { cx, parts, type DividerOrientation } from '@moderno/class-contract'

export interface DividerProps {
  orientation?: DividerOrientation
  /** Optional centered label (horizontal only). */
  label?: ReactNode
}

/** Visual/semantic separator, optionally labelled. Pure CSS, closed-prop. */
export function Divider({ orientation = 'horizontal', label }: DividerProps) {
  if (label && orientation === 'horizontal') {
    return (
      <div className={parts.divider.group} role="separator">
        {label}
      </div>
    )
  }
  return (
    <div
      className={cx.divider({ orientation })}
      role="separator"
      aria-orientation={orientation === 'vertical' ? 'vertical' : undefined}
    />
  )
}
