// packages/solid/src/skeleton.tsx
import type { JSX } from 'solid-js'

export interface SkeletonProps {
  variant?: 'text' | 'rect' | 'circle'
  width?: string | number
  height?: string | number
}

/** Loading placeholder with a shimmer. Decorative (aria-hidden). Pure CSS. */
export function Skeleton(props: SkeletonProps) {
  const style = (): JSX.CSSProperties => ({ width: props.width, height: props.height })
  return <span class={`md-skeleton md-skeleton--${props.variant ?? 'text'}`} style={style()} aria-hidden="true" />
}

// packages/react/src/skeleton.tsx
import type { CSSProperties } from 'react'

export interface SkeletonProps {
  variant?: 'text' | 'rect' | 'circle'
  /** CSS length; a number is treated as pixels. */
  width?: string | number
  /** CSS length; a number is treated as pixels. */
  height?: string | number
}

/** Loading placeholder with a shimmer. Decorative (aria-hidden). Pure CSS. */
export function Skeleton({ variant = 'text', width, height }: SkeletonProps) {
  const style: CSSProperties = { width, height }
  return <span className={`md-skeleton md-skeleton--${variant}`} style={style} aria-hidden="true" />
}
