// packages/solid/src/tabs.tsx
import { createContext, useContext, createMemo, createUniqueId, type JSX } from 'solid-js'
import * as tabs from '@zag-js/tabs'
import { useMachine, normalizeProps } from '@zag-js/solid'
import { parts } from '@moderno/class-contract'

type TabsApi = ReturnType<typeof tabs.connect>
const TabsContext = createContext<() => TabsApi>()

function useTabs(part: string): () => TabsApi {
  const api = useContext(TabsContext)
  if (!api) throw new Error(`Moderno: <Tabs.${part}> must be used inside <Tabs.Root>`)
  return api
}

export interface TabsRootProps {
  defaultValue?: string
  value?: string
  onValueChange?: (value: string) => void
  children: JSX.Element
}

function Root(props: TabsRootProps) {
  const service = useMachine(tabs.machine, {
    id: createUniqueId(),
    get defaultValue() {
      return props.defaultValue
    },
    get value() {
      return props.value
    },
    onValueChange: (d) => props.onValueChange?.(d.value),
  })
  const api = createMemo(() => tabs.connect(service, normalizeProps))
  return (
    <TabsContext.Provider value={api}>
      <div {...api().getRootProps()} class={parts.tabs.root}>
        {props.children}
      </div>
    </TabsContext.Provider>
  )
}

function List(props: { children: JSX.Element }) {
  const api = useTabs('List')
  return (
    <div {...api().getListProps()} class={parts.tabs.list}>
      {props.children}
    </div>
  )
}

function Trigger(props: { value: string; disabled?: boolean; children: JSX.Element }) {
  const api = useTabs('Trigger')
  return (
    <button {...api().getTriggerProps({ value: props.value, disabled: props.disabled })} class={parts.tabs.trigger}>
      {props.children}
    </button>
  )
}

function Content(props: { value: string; children: JSX.Element }) {
  const api = useTabs('Content')
  return (
    <div {...api().getContentProps({ value: props.value })} class={parts.tabs.content}>
      {props.children}
    </div>
  )
}

/** Compositional Tabs (ADR-0003): parts share one Zag machine via Solid context. */
export const Tabs = { Root, List, Trigger, Content }

// packages/react/src/tabs.tsx
import { createContext, useContext, useId, type ReactNode } from 'react'
import * as tabs from '@zag-js/tabs'
import { useMachine, normalizeProps } from '@zag-js/react'
import { parts } from '@moderno/class-contract'

type TabsApi = ReturnType<typeof tabs.connect>
const TabsContext = createContext<TabsApi | null>(null)

function useTabs(part: string): TabsApi {
  const api = useContext(TabsContext)
  if (!api) throw new Error(`Moderno: <Tabs.${part}> must be used inside <Tabs.Root>`)
  return api
}

export interface TabsRootProps {
  /** Uncontrolled initial selected tab. */
  defaultValue?: string
  /** Controlled selected tab. */
  value?: string
  onValueChange?: (value: string) => void
  children: ReactNode
}

function Root({ defaultValue, value, onValueChange, children }: TabsRootProps) {
  const service = useMachine(tabs.machine, {
    id: useId(),
    defaultValue,
    value,
    onValueChange: onValueChange ? (d) => onValueChange(d.value) : undefined,
  })
  const api = tabs.connect(service, normalizeProps)
  return (
    <TabsContext.Provider value={api}>
      <div {...api.getRootProps()} className={parts.tabs.root}>
        {children}
      </div>
    </TabsContext.Provider>
  )
}

function List({ children }: { children: ReactNode }) {
  const api = useTabs('List')
  return (
    <div {...api.getListProps()} className={parts.tabs.list}>
      {children}
    </div>
  )
}

function Trigger({ value, disabled, children }: { value: string; disabled?: boolean; children: ReactNode }) {
  const api = useTabs('Trigger')
  return (
    <button {...api.getTriggerProps({ value, disabled })} className={parts.tabs.trigger}>
      {children}
    </button>
  )
}

function Content({ value, children }: { value: string; children: ReactNode }) {
  const api = useTabs('Content')
  return (
    <div {...api.getContentProps({ value })} className={parts.tabs.content}>
      {children}
    </div>
  )
}

/** Compositional Tabs (per ADR-0003): anatomy parts share one Zag machine via context. */
export const Tabs = { Root, List, Trigger, Content }
