// packages/svelte/src/AccordionItemContent.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { getAccordionContext, getAccordionItemContext } from './accordion-context'
  import { parts } from '@moderno-ui/class-contract'

  let { children }: { children?: Snippet } = $props()
  const api = getAccordionContext()
  const item = getAccordionItemContext()
</script>

<div {...api().getItemContentProps(item)} class={parts.accordion.content}>{@render children?.()}</div>

// packages/vue/src/AccordionItemContent.vue
<script setup lang="ts">
import { inject } from 'vue'
import { AccordionKey, AccordionItemKey } from './accordion-context'
import { parts } from '@moderno/class-contract'

const api = inject(AccordionKey)!
const item = inject(AccordionItemKey)!
</script>

<template>
  <div v-bind="api.getItemContentProps(item)" :class="parts.accordion.content"><slot /></div>
</template>
