// packages/svelte/src/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLButtonAttributes } from 'svelte/elements'
  import { cx, type ButtonSize, type ButtonVariant } from '@moderno-ui/class-contract'

  let {
    variant,
    size,
    label,
    children,
    ...rest
  }: {
    variant?: ButtonVariant
    size?: ButtonSize
    label?: string
    children?: Snippet
  } & HTMLButtonAttributes = $props()
</script>

<button class={cx.button({ variant, size })} {...rest}>
  {#if label}{label}{:else}{@render children?.()}{/if}
</button>

// packages/vue/src/Button.vue
<script setup lang="ts">
import { cx, type ButtonSize, type ButtonVariant } from '@moderno-ui/class-contract'

const props = defineProps<{ variant?: ButtonVariant; size?: ButtonSize; label?: string }>()
</script>

<template>
  <button :class="cx.button({ variant: props.variant, size: props.size })">
    <template v-if="label">{{ label }}</template>
    <slot v-else />
  </button>
</template>
