// packages/svelte/src/Card.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { parts } from '@moderno-ui/class-contract'

  let {
    title,
    footer,
    children,
  }: {
    title?: Snippet
    footer?: Snippet
    children?: Snippet
  } = $props()
</script>

<div class={parts.card.root}>
  {#if title}<h3 class={parts.card.title}>{@render title()}</h3>{/if}
  {#if children}<div class={parts.card.body}>{@render children()}</div>{/if}
  {#if footer}<div class={parts.card.footer}>{@render footer()}</div>{/if}
</div>

// packages/vue/src/Card.vue
<script setup lang="ts">
import { useSlots } from 'vue'
import { parts } from '@moderno/class-contract'
const slots = useSlots()
</script>

<template>
  <div :class="parts.card.root">
    <h3 v-if="slots.title" :class="parts.card.title"><slot name="title" /></h3>
    <div v-if="slots.default" :class="parts.card.body"><slot /></div>
    <div v-if="slots.footer" :class="parts.card.footer"><slot name="footer" /></div>
  </div>
</template>
