// packages/svelte/src/CarouselIndicatorGroup.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { getCarouselContext } from './carousel-context'
  import { parts } from '@moderno/class-contract'

  let { children }: { children: Snippet<[index: number]> } = $props()
  const api = getCarouselContext()
</script>

<div {...api().getIndicatorGroupProps()} class={parts.carousel.indicatorGroup}>
  {#each api().pageSnapPoints as _, index (index)}
    {@render children(index)}
  {/each}
</div>

// packages/vue/src/CarouselIndicatorGroup.vue
<script setup lang="ts">
import { useCarousel } from './carousel-context'
import { parts } from '@moderno/class-contract'

const api = useCarousel('IndicatorGroup')
</script>

<template>
  <div v-bind="api.getIndicatorGroupProps()" :class="parts.carousel.indicatorGroup">
    <template v-for="(_, index) in api.pageSnapPoints" :key="index">
      <slot :index="index" />
    </template>
  </div>
</template>
