// packages/svelte/src/CarouselNextTrigger.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { getCarouselContext } from './carousel-context'
  import { parts } from '@moderno-ui/class-contract'

  let { children }: { children?: Snippet } = $props()
  const api = getCarouselContext()
</script>

<button {...api().getNextTriggerProps()} class={parts.carousel.nextTrigger}>
  {#if children}{@render children()}{:else}›{/if}
</button>

// packages/vue/src/CarouselNextTrigger.vue
<script setup lang="ts">
import { useCarousel } from './carousel-context'
import { parts } from '@moderno/class-contract'

const api = useCarousel('NextTrigger')
</script>

<template>
  <button v-bind="api.getNextTriggerProps()" :class="parts.carousel.nextTrigger"><slot>›</slot></button>
</template>
