// packages/svelte/src/Checkbox.svelte
<script lang="ts">
  import * as checkbox from '@zag-js/checkbox'
  import { useMachine, normalizeProps } from '@zag-js/svelte'
  import { parts } from '@moderno/class-contract'

  type CheckedState = boolean | 'indeterminate'

  let {
    label,
    defaultChecked,
    checked = $bindable(),
    onCheckedChange,
    disabled,
    invalid,
    required,
    name,
    value,
  }: {
    label?: string
    defaultChecked?: CheckedState
    checked?: CheckedState
    onCheckedChange?: (checked: CheckedState) => void
    disabled?: boolean
    invalid?: boolean
    required?: boolean
    name?: string
    value?: string
  } = $props()

  const id = $props.id()
  const service = useMachine(checkbox.machine, {
    id,
    get defaultChecked() {
      return defaultChecked
    },
    get checked() {
      return checked
    },
    get disabled() {
      return disabled
    },
    get invalid() {
      return invalid
    },
    get required() {
      return required
    },
    get name() {
      return name
    },
    get value() {
      return value
    },
    onCheckedChange(d) {
      checked = d.checked
      onCheckedChange?.(d.checked)
    },
  })
  const api = $derived(checkbox.connect(service, normalizeProps))
</script>

<label {...api.getRootProps()} class={parts.checkbox.root}>
  <input {...api.getHiddenInputProps()} />
  <span {...api.getControlProps()} class={parts.checkbox.control}>
    <span {...api.getIndicatorProps()} class={parts.checkbox.indicator}>{api.indeterminate ? '–' : '✓'}</span>
  </span>
  {#if label != null}
    <span {...api.getLabelProps()} class={parts.checkbox.label}>{label}</span>
  {/if}
</label>

// packages/vue/src/Checkbox.vue
<script setup lang="ts">
import { computed, useId } from 'vue'
import * as checkbox from '@zag-js/checkbox'
import { useMachine, normalizeProps } from '@zag-js/vue'
import { parts } from '@moderno/class-contract'

type CheckedState = boolean | 'indeterminate'

defineOptions({ inheritAttrs: false })

const props = defineProps<{
  label?: string
  defaultChecked?: CheckedState
  modelValue?: CheckedState
  disabled?: boolean
  invalid?: boolean
  required?: boolean
  name?: string
  value?: string
}>()
const emit = defineEmits<{ 'update:modelValue': [CheckedState] }>()

const service = useMachine(checkbox.machine, {
  id: useId(),
  get defaultChecked() {
    return props.defaultChecked
  },
  get checked() {
    return props.modelValue
  },
  get disabled() {
    return props.disabled
  },
  get invalid() {
    return props.invalid
  },
  get required() {
    return props.required
  },
  get name() {
    return props.name
  },
  get value() {
    return props.value
  },
  onCheckedChange(d) {
    emit('update:modelValue', d.checked)
  },
})
const api = computed(() => checkbox.connect(service, normalizeProps))
</script>

<template>
  <label v-bind="api.getRootProps()" :class="parts.checkbox.root">
    <input v-bind="api.getHiddenInputProps()" />
    <span v-bind="api.getControlProps()" :class="parts.checkbox.control">
      <span v-bind="api.getIndicatorProps()" :class="parts.checkbox.indicator">{{ api.indeterminate ? '–' : '✓' }}</span>
    </span>
    <span v-if="label != null" v-bind="api.getLabelProps()" :class="parts.checkbox.label">{{ label }}</span>
  </label>
</template>
