// packages/svelte/src/DatePickerClearTrigger.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { getDatePickerContext } from './date-picker-context'
  import { parts } from '@moderno-ui/class-contract'

  let { children }: { children?: Snippet } = $props()
  const api = getDatePickerContext()
</script>

<button {...api().getClearTriggerProps()} class={parts.datepicker.clearTrigger}>
  {#if children}{@render children()}{:else}✕{/if}
</button>

// packages/vue/src/DatePickerClearTrigger.vue
<script setup lang="ts">
import { useDatePicker } from './date-picker-context'
import { parts } from '@moderno/class-contract'

const api = useDatePicker('ClearTrigger')
</script>

<template>
  <button v-bind="api.getClearTriggerProps()" :class="parts.datepicker.clearTrigger">
    <slot>✕</slot>
  </button>
</template>
