// packages/svelte/src/Indicator.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { cx, parts, type IndicatorVariant } from '@moderno-ui/class-contract'

  let {
    variant,
    pulse,
    children,
  }: {
    variant?: IndicatorVariant
    pulse?: boolean
    children?: Snippet
  } = $props()
</script>

<span class={cx.indicator({ variant, pulse })}>
  <span class={parts.indicator.dot}></span>
  {@render children?.()}
</span>

// packages/vue/src/Indicator.vue
<script setup lang="ts">
import { cx, parts, type IndicatorVariant } from '@moderno/class-contract'

const props = defineProps<{
  variant?: IndicatorVariant
  pulse?: boolean
}>()
</script>

<template>
  <span :class="cx.indicator({ variant: props.variant, pulse: props.pulse })">
    <span :class="parts.indicator.dot" />
    <slot />
  </span>
</template>
