// packages/svelte/src/Popover.svelte
<script lang="ts">
  import * as popover from '@zag-js/popover'
  import { useMachine, normalizeProps, portal } from '@zag-js/svelte'
  import { cx, parts } from '@moderno/class-contract'

  let {
    triggerLabel,
    title,
    content,
    closeLabel = 'Close',
  }: {
    triggerLabel: string
    title?: string
    content: string
    closeLabel?: string
  } = $props()

  const id = $props.id()
  const service = useMachine(popover.machine, { id })
  const api = $derived(popover.connect(service, normalizeProps))
</script>

<button {...api.getTriggerProps()} class={cx.button({ variant: 'secondary', size: 'sm' })}>{triggerLabel}</button>
{#if api.open}
  <div use:portal {...api.getPositionerProps()} class={parts.popover.positioner}>
    <div {...api.getContentProps()} class={parts.popover.content}>
      <div {...api.getArrowProps()} class={parts.popover.arrow}>
        <div {...api.getArrowTipProps()}></div>
      </div>
      {#if title}
        <p {...api.getTitleProps()} class={parts.popover.title}>{title}</p>
      {/if}
      <div {...api.getDescriptionProps()} class={parts.popover.body}>{content}</div>
      <button {...api.getCloseTriggerProps()} class={parts.popover.close} aria-label={closeLabel}>✕</button>
    </div>
  </div>
{/if}

// packages/vue/src/Popover.vue
<script setup lang="ts">
import { computed, useId } from 'vue'
import * as popover from '@zag-js/popover'
import { useMachine, normalizeProps } from '@zag-js/vue'
import { cx, parts } from '@moderno-ui/class-contract'

// Trigger renders inline; panel is teleported to the body.
defineOptions({ inheritAttrs: false })

const props = withDefaults(
  defineProps<{ triggerLabel: string; title?: string; content: string; closeLabel?: string }>(),
  { closeLabel: 'Close' },
)

const service = useMachine(popover.machine, { id: useId() })
const api = computed(() => popover.connect(service, normalizeProps))
</script>

<template>
  <button v-bind="api.getTriggerProps()" :class="cx.button({ variant: 'secondary', size: 'sm' })">{{ triggerLabel }}</button>
  <Teleport v-if="api.open" to="body">
    <div v-bind="api.getPositionerProps()" :class="parts.popover.positioner">
      <div v-bind="api.getContentProps()" :class="parts.popover.content">
        <div v-bind="api.getArrowProps()" :class="parts.popover.arrow">
          <div v-bind="api.getArrowTipProps()" />
        </div>
        <p v-if="title" v-bind="api.getTitleProps()" :class="parts.popover.title">{{ title }}</p>
        <div v-bind="api.getDescriptionProps()" :class="parts.popover.body">{{ content }}</div>
        <button v-bind="api.getCloseTriggerProps()" :class="parts.popover.close" :aria-label="closeLabel">✕</button>
      </div>
    </div>
  </Teleport>
</template>
