// packages/svelte/src/SelectItem.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { getSelectContext, type SelectItem } from './select-context'
  import { parts } from '@moderno-ui/class-contract'

  let { item, children }: { item: SelectItem; children?: Snippet } = $props()
  const api = getSelectContext()
</script>

<li {...api().getItemProps({ item })} class={parts.select.item}>
  <span {...api().getItemTextProps({ item })} class={parts.select.itemText}>
    {#if children}{@render children()}{:else}{item.label}{/if}
  </span>
  <span {...api().getItemIndicatorProps({ item })} class={parts.select.itemIndicator} aria-hidden="true">✓</span>
</li>

// packages/vue/src/SelectItem.vue
<script setup lang="ts">
import { useSelect, type SelectItem } from './select-context'
import { parts } from '@moderno/class-contract'

const props = defineProps<{ item: SelectItem }>()
const api = useSelect('Item')
</script>

<template>
  <li v-bind="api.getItemProps({ item: props.item })" :class="parts.select.item">
    <span v-bind="api.getItemTextProps({ item: props.item })" :class="parts.select.itemText">
      <slot>{{ props.item.label }}</slot>
    </span>
    <span v-bind="api.getItemIndicatorProps({ item: props.item })" :class="parts.select.itemIndicator" aria-hidden="true">✓</span>
  </li>
</template>
