// packages/svelte/src/SelectContent.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { portal } from '@zag-js/svelte'
  import { getSelectContext } from './select-context'
  import { parts } from '@moderno/class-contract'

  let { children }: { children?: Snippet } = $props()
  const api = getSelectContext()
</script>

{#if api().open}
  <div use:portal {...api().getPositionerProps()} class={parts.select.positioner}>
    <ul {...api().getContentProps()} class={parts.select.content}>{@render children?.()}</ul>
  </div>
{/if}

// packages/vue/src/SelectContent.vue
<script setup lang="ts">
import { useSelect } from './select-context'
import { parts } from '@moderno-ui/class-contract'

// Content is teleported to the body; trigger stays in flow.
defineOptions({ inheritAttrs: false })
const api = useSelect('Content')
</script>

<template>
  <Teleport v-if="api.open" to="body">
    <div v-bind="api.getPositionerProps()" :class="parts.select.positioner">
      <ul v-bind="api.getContentProps()" :class="parts.select.content"><slot /></ul>
    </div>
  </Teleport>
</template>
