// packages/svelte/src/Skeleton.svelte
<script lang="ts">
  import { cx, type SkeletonVariant } from '@moderno-ui/class-contract'

  let {
    variant,
    width,
    height,
  }: {
    variant?: SkeletonVariant
    width?: string | number
    height?: string | number
  } = $props()

  const len = (v: string | number | undefined) => (typeof v === 'number' ? `${v}px` : v)
  const style = $derived(
    [width != null && `width:${len(width)}`, height != null && `height:${len(height)}`].filter(Boolean).join(';'),
  )
</script>

<span class={cx.skeleton({ variant })} {style} aria-hidden="true"></span>

// packages/vue/src/Skeleton.vue
<script setup lang="ts">
import { computed } from 'vue'
import { cx, type SkeletonVariant } from '@moderno-ui/class-contract'

const props = defineProps<{
  variant?: SkeletonVariant
  width?: string | number
  height?: string | number
}>()

const len = (v: string | number | undefined) => (typeof v === 'number' ? `${v}px` : v)
const style = computed(() => ({ width: len(props.width), height: len(props.height) }))
</script>

<template>
  <span :class="cx.skeleton({ variant: props.variant })" :style="style" aria-hidden="true" />
</template>
