// packages/registry/blocks/hero/Hero.solid.tsx
import { Button } from '@moderno/solid'
import type { JSX } from 'solid-js'

export interface HeroProps {
  kicker?: string
  title?: string
  subtitle?: string
  ctaLabel?: string
  onCta?: () => void
}

/**
 * Moderno block — Hero (Solid). Copy-paste; edit freely.
 * Uses the Button primitive + Moderno tokens (--md-* custom properties).
 */
export function Hero(props: HeroProps) {
  const sectionStyle: JSX.CSSProperties = {
    padding: '96px 24px',
    'text-align': 'center',
    background: 'var(--md-surface-base)',
    'border-bottom': '1px solid var(--md-border-default)',
  }
  return (
    <section style={sectionStyle}>
      <p
        style={{
          'font-size': 'var(--md-text-label-sm)',
          'letter-spacing': '0.14em',
          'text-transform': 'uppercase',
          color: 'var(--md-text-secondary)',
          margin: '0 0 16px',
        }}
      >
        {props.kicker ?? 'Moderno'}
      </p>
      <h1
        style={{
          'font-family': 'var(--md-font-serif)',
          'font-size': '48px',
          'line-height': 1.05,
          'letter-spacing': '-0.02em',
          color: 'var(--md-text-primary)',
          margin: '0 auto 16px',
          'max-width': '16ch',
        }}
      >
        {props.title ?? 'Construye productos, no componentes.'}
      </h1>
      <p
        style={{
          'font-size': 'var(--md-text-body-lg)',
          'line-height': 'var(--md-text-body-lg-lh)',
          color: 'var(--md-text-secondary)',
          margin: '0 auto 32px',
          'max-width': '52ch',
        }}
      >
        {props.subtitle ??
          'Un sistema de diseño agnóstico al framework: un comportamiento y un look, usables desde React, Vue, Svelte y Solid.'}
      </p>
      <Button label={props.ctaLabel ?? 'Empezar ahora'} size="lg" onClick={() => props.onCta?.()} />
    </section>
  )
}

// packages/registry/blocks/marketing/hero/Hero.tsx
import { Button } from '@moderno-ui/react'

export interface HeroProps {
  kicker?: string
  title?: string
  subtitle?: string
  ctaLabel?: string
  onCta?: () => void
}

/**
 * Moderno block — Hero. Copy-paste; edit freely.
 * Uses the Button primitive + Moderno tokens (--md-* custom properties).
 */
export function Hero({
  kicker = 'Moderno',
  title = 'Construye productos, no componentes.',
  subtitle = 'Un sistema de diseño agnóstico al framework: un comportamiento y un look, usables desde React, Vue, Svelte y Solid.',
  ctaLabel = 'Empezar ahora',
  onCta,
}: HeroProps) {
  return (
    <section
      style={{
        padding: '96px 24px',
        textAlign: 'center',
        background: 'var(--md-surface-base)',
        borderBottom: '1px solid var(--md-border-default)',
      }}
    >
      <p
        style={{
          fontSize: 'var(--md-text-label-sm)',
          letterSpacing: '0.14em',
          textTransform: 'uppercase',
          color: 'var(--md-text-secondary)',
          margin: '0 0 16px',
        }}
      >
        {kicker}
      </p>
      <h1
        style={{
          fontFamily: 'var(--md-font-serif)',
          fontSize: '48px',
          lineHeight: 1.05,
          letterSpacing: '-0.02em',
          color: 'var(--md-text-primary)',
          margin: '0 auto 16px',
          maxWidth: '16ch',
        }}
      >
        {title}
      </h1>
      <p
        style={{
          fontSize: 'var(--md-text-body-lg)',
          lineHeight: 'var(--md-text-body-lg-lh)',
          color: 'var(--md-text-secondary)',
          margin: '0 auto 32px',
          maxWidth: '52ch',
        }}
      >
        {subtitle}
      </p>
      <Button label={ctaLabel} size="lg" onClick={onCta} />
    </section>
  )
}
