// packages/react/src/card.tsx
import type { ReactNode } from 'react'
import { parts } from '@moderno-ui/class-contract'

export interface CardProps {
  title?: ReactNode
  footer?: ReactNode
  children?: ReactNode
}

/** Container surface that groups related content and actions. Closed-prop. */
export function Card({ title, footer, children }: CardProps) {
  return (
    <div className={parts.card.root}>
      {title ? <h3 className={parts.card.title}>{title}</h3> : null}
      {children ? <div className={parts.card.body}>{children}</div> : null}
      {footer ? <div className={parts.card.footer}>{footer}</div> : null}
    </div>
  )
}

// packages/solid/src/card.tsx
import { Show, type JSX } from 'solid-js'
import { parts } from '@moderno-ui/class-contract'

export interface CardProps {
  title?: JSX.Element
  footer?: JSX.Element
  children?: JSX.Element
}

/** Container surface that groups related content and actions. Closed-prop. */
export function Card(props: CardProps) {
  return (
    <div class={parts.card.root}>
      <Show when={props.title}>
        <h3 class={parts.card.title}>{props.title}</h3>
      </Show>
      <Show when={props.children}>
        <div class={parts.card.body}>{props.children}</div>
      </Show>
      <Show when={props.footer}>
        <div class={parts.card.footer}>{props.footer}</div>
      </Show>
    </div>
  )
}
