// packages/react/src/input.tsx
import { useId, type InputHTMLAttributes, type ReactNode } from 'react'
import { cx, parts } from '@moderno-ui/class-contract'

export interface InputProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'children'> {
  label?: ReactNode
  hint?: ReactNode
  /** Error message; replaces the hint and flags the field invalid. */
  error?: ReactNode
}

/** Single-line text field with label, hint and error. Pure CSS, closed-prop. */
export function Input({ label, hint, error, id, className, ...props }: InputProps) {
  const autoId = useId()
  const inputId = id ?? autoId
  const msgId = `${inputId}-msg`
  const cls = [cx.input({ error: !!error }), className].filter(Boolean).join(' ')
  return (
    <div>
      {label ? (
        <label className={parts.field.label} htmlFor={inputId}>
          {label}
        </label>
      ) : null}
      <input
        id={inputId}
        className={cls}
        aria-invalid={error ? true : undefined}
        aria-describedby={error || hint ? msgId : undefined}
        {...props}
      />
      {error ? (
        <p className={parts.field.error} id={msgId}>
          {error}
        </p>
      ) : hint ? (
        <p className={parts.field.hint} id={msgId}>
          {hint}
        </p>
      ) : null}
    </div>
  )
}

// packages/solid/src/input.tsx
import { splitProps, createUniqueId, Show, type JSX } from 'solid-js'
import { cx, parts } from '@moderno-ui/class-contract'

export interface InputProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'children'> {
  label?: JSX.Element
  hint?: JSX.Element
  error?: JSX.Element
}

/** Single-line text field with label, hint and error. Pure CSS, closed-prop. */
export function Input(props: InputProps) {
  const [local, rest] = splitProps(props, ['label', 'hint', 'error', 'id', 'class'])
  const fallbackId = createUniqueId()
  const inputId = () => local.id ?? fallbackId
  const msgId = () => `${inputId()}-msg`
  const cls = () => [cx.input({ error: !!local.error }), local.class].filter(Boolean).join(' ')
  return (
    <div>
      <Show when={local.label}>
        <label class={parts.field.label} for={inputId()}>
          {local.label}
        </label>
      </Show>
      <input
        id={inputId()}
        class={cls()}
        aria-invalid={local.error ? true : undefined}
        aria-describedby={local.error || local.hint ? msgId() : undefined}
        {...rest}
      />
      <Show when={local.error} fallback={<Show when={local.hint}><p class={parts.field.hint} id={msgId()}>{local.hint}</p></Show>}>
        <p class={parts.field.error} id={msgId()}>
          {local.error}
        </p>
      </Show>
    </div>
  )
}
