// packages/react/src/select.tsx
import { createContext, useContext, useId, useMemo, type ReactNode } from 'react'
import * as select from '@zag-js/select'
import { useMachine, normalizeProps, Portal } from '@zag-js/react'
import { parts } from '@moderno/class-contract'

export interface SelectItem {
  label: string
  value: string
  disabled?: boolean
}

type SelectApi = ReturnType<typeof select.connect>
const SelectContext = createContext<SelectApi | null>(null)

function useSelect(part: string): SelectApi {
  const api = useContext(SelectContext)
  if (!api) throw new Error(`Moderno: <Select.${part}> must be used inside <Select.Root>`)
  return api
}

export interface SelectRootProps {
  /** The options to choose from. */
  items: SelectItem[]
  /** Uncontrolled initial selected keys. */
  defaultValue?: string[]
  /** Controlled selected keys. */
  value?: string[]
  multiple?: boolean
  disabled?: boolean
  onValueChange?: (value: string[]) => void
  children: ReactNode
}

function Root({ items, defaultValue, value, multiple, disabled, onValueChange, children }: SelectRootProps) {
  const collection = useMemo(() => select.collection({ items }), [items])
  const service = useMachine(select.machine, {
    id: useId(),
    collection,
    defaultValue,
    value,
    multiple,
    disabled,
    onValueChange: onValueChange ? (d) => onValueChange(d.value) : undefined,
  })
  const api = select.connect(service, normalizeProps)
  return (
    <SelectContext.Provider value={api}>
      <div {...api.getRootProps()} className={parts.select.root}>
        {children}
      </div>
    </SelectContext.Provider>
  )
}

function Label({ children }: { children: ReactNode }) {
  const api = useSelect('Label')
  return (
    <label {...api.getLabelProps()} className={parts.select.label}>
      {children}
    </label>
  )
}

function Trigger({ placeholder = 'Select…' }: { placeholder?: string }) {
  const api = useSelect('Trigger')
  return (
    <div {...api.getControlProps()} className={parts.select.control}>
      <button {...api.getTriggerProps()} className={parts.select.trigger}>
        <span {...api.getValueTextProps()} className={parts.select.value}>
          {api.empty ? placeholder : api.valueAsString}
        </span>
        <span {...api.getIndicatorProps()} className={parts.select.indicator} aria-hidden="true">
          ▾
        </span>
      </button>
    </div>
  )
}

function Content({ children }: { children: ReactNode }) {
  const api = useSelect('Content')
  if (!api.open) return null
  return (
    <Portal>
      <div {...api.getPositionerProps()} className={parts.select.positioner}>
        <ul {...api.getContentProps()} className={parts.select.content}>
          {children}
        </ul>
      </div>
    </Portal>
  )
}

function Item({ item, children }: { item: SelectItem; children?: ReactNode }) {
  const api = useSelect('Item')
  return (
    <li {...api.getItemProps({ item })} className={parts.select.item}>
      <span {...api.getItemTextProps({ item })} className={parts.select.itemText}>
        {children ?? item.label}
      </span>
      <span {...api.getItemIndicatorProps({ item })} className={parts.select.itemIndicator} aria-hidden="true">
        ✓
      </span>
    </li>
  )
}

/** Compositional Select (ADR-0003): parts share one Zag machine via context. */
export const Select = { Root, Label, Trigger, Content, Item }

// packages/solid/src/select.tsx
import { createContext, useContext, createMemo, createUniqueId, Show, type JSX } from 'solid-js'
import { Portal } from 'solid-js/web'
import * as select from '@zag-js/select'
import { useMachine, normalizeProps } from '@zag-js/solid'
import { parts } from '@moderno/class-contract'

export interface SelectItem {
  label: string
  value: string
  disabled?: boolean
}

type SelectApi = ReturnType<typeof select.connect>
const SelectContext = createContext<() => SelectApi>()

function useSelect(part: string): () => SelectApi {
  const api = useContext(SelectContext)
  if (!api) throw new Error(`Moderno: <Select.${part}> must be used inside <Select.Root>`)
  return api
}

export interface SelectRootProps {
  items: SelectItem[]
  defaultValue?: string[]
  value?: string[]
  multiple?: boolean
  disabled?: boolean
  onValueChange?: (value: string[]) => void
  children: JSX.Element
}

function Root(props: SelectRootProps) {
  const collection = createMemo(() => select.collection({ items: props.items }))
  const service = useMachine(select.machine, {
    id: createUniqueId(),
    get collection() {
      return collection()
    },
    get defaultValue() {
      return props.defaultValue
    },
    get value() {
      return props.value
    },
    get multiple() {
      return props.multiple
    },
    get disabled() {
      return props.disabled
    },
    onValueChange: (d) => props.onValueChange?.(d.value),
  })
  const api = createMemo(() => select.connect(service, normalizeProps))
  return (
    <SelectContext.Provider value={api}>
      <div {...api().getRootProps()} class={parts.select.root}>
        {props.children}
      </div>
    </SelectContext.Provider>
  )
}

function Label(props: { children: JSX.Element }) {
  const api = useSelect('Label')
  return (
    <label {...api().getLabelProps()} class={parts.select.label}>
      {props.children}
    </label>
  )
}

function Trigger(props: { placeholder?: string }) {
  const api = useSelect('Trigger')
  const placeholder = () => props.placeholder ?? 'Select…'
  return (
    <div {...api().getControlProps()} class={parts.select.control}>
      <button {...api().getTriggerProps()} class={parts.select.trigger}>
        <span {...api().getValueTextProps()} class={parts.select.value}>
          {api().empty ? placeholder() : api().valueAsString}
        </span>
        <span {...api().getIndicatorProps()} class={parts.select.indicator} aria-hidden="true">
          ▾
        </span>
      </button>
    </div>
  )
}

function Content(props: { children: JSX.Element }) {
  const api = useSelect('Content')
  return (
    <Show when={api().open}>
      <Portal>
        <div {...api().getPositionerProps()} class={parts.select.positioner}>
          <ul {...api().getContentProps()} class={parts.select.content}>
            {props.children}
          </ul>
        </div>
      </Portal>
    </Show>
  )
}

function Item(props: { item: SelectItem; children?: JSX.Element }) {
  const api = useSelect('Item')
  return (
    <li {...api().getItemProps({ item: props.item })} class={parts.select.item}>
      <span {...api().getItemTextProps({ item: props.item })} class={parts.select.itemText}>
        {props.children ?? props.item.label}
      </span>
      <span {...api().getItemIndicatorProps({ item: props.item })} class={parts.select.itemIndicator} aria-hidden="true">
        ✓
      </span>
    </li>
  )
}

/** Compositional Select (ADR-0003): parts share one Zag machine via Solid context. */
export const Select = { Root, Label, Trigger, Content, Item }
