// apps/docs/src/demos/react/flows/AuthDemo.tsx
import { AuthExample, type AuthExampleProps } from '@moderno/registry/flows/auth/Auth.example.tsx'

// `step` is a plain string prop passed from the MDX doc across the
// Astro-island boundary (which serializes to JSON) so each screen can be
// demoed individually alongside the full assembled journey.
export default function AuthDemo({ step }: { step?: AuthExampleProps['initialStep'] }) {
  return <AuthExample initialStep={step} />
}

// apps/docs/src/demos/svelte/flows/AuthDemo.svelte
<script lang="ts">
  import AuthExample from '@moderno/registry/flows/auth/Auth.example.svelte'

  // `step` is a plain string prop passed from the MDX doc across the
  // Astro-island boundary (which serializes to JSON) so each screen can be
  // demoed individually alongside the full assembled journey.
  let { step = 'sign-in' }: { step?: string } = $props()
</script>

<AuthExample initialStep={step} />
