// apps/docs/src/demos/react/flows/ReferralDemo.tsx
import { ReferralExample, type ReferralExampleProps } from '@moderno-ui/registry/flows/referral/Referral.example.tsx'

// `step` is a plain string prop passed from the MDX doc across the
// Astro-island boundary (which serializes to JSON) so each screen can be
// demoed individually alongside the full assembled journey.
export default function ReferralDemo({ step }: { step?: ReferralExampleProps['initialStep'] }) {
  return <ReferralExample initialStep={step} />
}

// apps/docs/src/demos/svelte/flows/ReferralDemo.svelte
<script lang="ts">
  import ReferralExample from '@moderno-ui/registry/flows/referral/Referral.example.svelte'

  // `step` is a plain string prop passed from the MDX doc across the
  // Astro-island boundary (which serializes to JSON) so each screen can be
  // demoed individually alongside the full assembled journey.
  let { step = 'invite' }: { step?: string } = $props()
</script>

<ReferralExample initialStep={step} />
