// apps/docs/src/demos/vue/flows/ReferralDemo.vue
<script setup lang="ts">
import ReferralExample from '@moderno-ui/registry/flows/referral/Referral.example.vue'

// `step` is a plain string prop passed from the MDX doc across the
// Astro-island boundary (which serializes to JSON) so each screen can be
// demoed individually alongside the full assembled journey.
const props = withDefaults(defineProps<{ step?: string }>(), { step: 'invite' })
</script>

<template>
  <ReferralExample :initial-step="props.step" />
</template>

// apps/docs/src/demos/svelte/flows/ReferralDemo.svelte
<script lang="ts">
  import ReferralExample from '@moderno-ui/registry/flows/referral/Referral.example.svelte'

  // `step` is a plain string prop passed from the MDX doc across the
  // Astro-island boundary (which serializes to JSON) so each screen can be
  // demoed individually alongside the full assembled journey.
  let { step = 'invite' }: { step?: string } = $props()
</script>

<ReferralExample initialStep={step} />
