// apps/docs/src/demos/svelte/flows/CheckoutDemo.svelte
<script lang="ts">
  import CheckoutExample from '@moderno-ui/registry/flows/checkout/Checkout.example.svelte'

  // `step` is a plain string prop passed from the MDX doc across the
  // Astro-island boundary (which serializes to JSON) so each screen can be
  // demoed individually alongside the full assembled journey.
  let { step = 'cart' }: { step?: string } = $props()
</script>

<CheckoutExample initialStep={step} />

// apps/docs/src/demos/solid/flows/CheckoutDemo.tsx
import { CheckoutExample, type CheckoutExampleProps } from '@moderno-ui/registry/flows/checkout/Checkout.example.solid.tsx'

// `step` is a plain string prop passed from the MDX doc across the
// Astro-island boundary (which serializes to JSON) so each screen can be
// demoed individually alongside the full assembled journey.
export default function CheckoutDemo(props: { step?: CheckoutExampleProps['initialStep'] }) {
  return <CheckoutExample initialStep={props.step} />
}
