// apps/docs/src/demos/react/DatePickerDemo.tsx
import { DatePicker } from '@moderno-ui/react'

export default function DatePickerDemo() {
  return (
    <div style={{ maxWidth: 280 }}>
      <DatePicker.Root defaultValue={['2024-01-15']}>
        <DatePicker.Label>Fecha de entrega</DatePicker.Label>
        <DatePicker.Control>
          <DatePicker.Input />
          <DatePicker.Trigger />
        </DatePicker.Control>
        <DatePicker.Content />
      </DatePicker.Root>
    </div>
  )
}

// apps/docs/src/demos/svelte/DatePickerDemo.svelte
<script lang="ts">
  import { DatePicker } from '@moderno/svelte'
</script>

<div style="max-width: 280px">
  <DatePicker.Root defaultValue={['2024-01-15']}>
    <DatePicker.Label>Fecha de entrega</DatePicker.Label>
    <DatePicker.Control>
      <DatePicker.Input />
      <DatePicker.Trigger />
    </DatePicker.Control>
    <DatePicker.Content />
  </DatePicker.Root>
</div>
